language: python

os: linux

python:
    - "3.6"

install:
    - sudo apt-get install python3-dev
    - sudo apt-get install gcc
    - sudo -H pip install pybind11
    - sudo python setup.py install

script:
    - pytest -v
