language: python

os: linux

python:
    - "3.6"

install:
    - pip install pybind11
    - pip install .

script:
    - python -c 'import pybind11; print(pybind11)'
    - python -c 'import pybind_example; print(pybind_example)'
