language: python

os: linux

python:
    - "3.6"

install:
    - pip install pybind11

script:
    - ls
    - which python
    - which gcc
    - python -c 'import pybind11; print(pybind11)'
    - sudo python setup.py install
    - python -c 'import pybind_example; print(pybind_example)'
