language: python

os: linux

python:
    - "3.6"

install:
    - pip install pybind11
    - pip install pytest
    - pip install --install-option="--codecov" -e .

script:
    - pytest -v
    - gcov -r build/temp.linux-x86_64-3.6/*

after_success:
    - bash <(curl -s https://codecov.io/bash)
