language: python

os: linux

python:
    - "3.6"

install:
    - sudo apt-get install python3-dev
    - sudo apt-get install gcc
    - sudo -H pip install pybind11
    - sudo -H pip install pytest
    - sudo python3 setup.py build
    - ls
    - ls build/
    - sudo python3 setup.py install

script:
    - pytest -v
