language: python

os: linux

python:
    - "3.6"

install:
    - pip install pybind11
    - pip install pytest
    - pip install --install-option="--codecov" .

script:
    - ls
    - pytest -v
    - ls
