language: python

os: linux

python:
    - "3.6"

install:
    - sudo apt-get install gcc
    - sudo apt-get install python3-dev
    - sudo apt-get install python3-pip
    - sudo -H pip3  install pybind11
    - sudo -H pip3  install pytest
    - sudo python3 setup.py build
    - ls
    - ls build/
    - "mv build/lib.linux-x86_64-3.4/* ."
    - ls
    - sudo python3 setup.py install

script:
    - pytest -v
